use HGI_MUASAMCONG;

CREATE TABLE DANHSACHGOITHAU
(
	MA_TBMT varchar(100) primary key,
	TENGOITHAU NVARCHAR(4000),
	BENMOITHAU NVARCHAR(4000),
	CHUDAUTU NVARCHAR(4000),
	NGAYDANGTAITHONGBAOTEXT NVARCHAR(4000),
	NGAYDANGTAITHONGBAO DATE,
	LINHVUC NVARCHAR(4000),
	DIADIEM NVARCHAR(4000),
	THOIDIEMDONGTHAU NVARCHAR(4000),
	HINHTHUCDUTHAU NVARCHAR(4000),
	NHATRUNGTHAU NVARCHAR(4000),
	GIATRUNGTHAU NVARCHAR(4000),
	NGAYPHEDUYETKQLCNT NVARCHAR(4000),
	TRANGTHAIGOITHAU NVARCHAR(4000),
	ISGET int default 0,
	URL NVARCHAR(4000),
	CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX indexDanhSachGoiThau ON 
danhsachgoithau(NGAYDANGTAITHONGBAO,NHATRUNGTHAU,DIADIEM,TRANGTHAIGOITHAU,ISGET);

select * from DANHSACHGOITHAU
insert into DANHSACHGOITHAU (MA_TBMT) values ('bt1')